# These are supported funding model platforms

github: Diamond-xv0 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ["https://paypal.me/KrystalMCNetwork?country.x=CL&locale.x=es_XC"] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
