ShootingStar:
  item: nether_star
  name: "&e&lStar"
  lore:
    - "&eA bright shooting star"
  particles: glow
  sound: BLOCK_AMETHYST_BLOCK_BREAK
  probability: 0.1   # You can select between 0.1 to 10
  altitude: "25-50"  # The altitude from which the star will fall
  sky: true         # if set to true, it will check for open sky to spawn (it's in beta)
  time: night   # Does it spawn during the day or at night?
  world: world    # The world where it can spawn