name: ShootingStarPlugin
main: com.shootingstar.quesadilla.ShootingStarPlugin
version: 1.2.0
api-version: "1.20"
commands:
  sh:
    description: Comando principal
    usage: /sh <subcomando> [args]
    aliases: [shootingstar]
    permission: shootingstars.admin